---
# tasks file for roles/omero-runtime

- name: omero python deps | distribution packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - Cython
    - numpy
    - python-jinja2
    - python-matplotlib
    - python-numexpr
    - python-pillow
    - python-pip
    - python-tables
    - python-yaml
    - scipy

  when: "{{ omero_python_deps_recommended }}"
